### ISSUE TITLE
As an instructor, I want to discover curated syllabi so I can reuse proven out pedagogy for my proposed course.

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1260]
### Background

Professors need a way to start from available syllabi for their proposed classroom. This includes viewing, cloning, and editing existing syllabi to model their curriculum after. 

### Goal

> Create a discovery page for professors to browse and duplicate pre-made Syllabi

### Acceptance criteria

- [x] Professors should be able to see a curated set (3) of Syllabi for a variety of learning goals 
- [x] Professors should be able to clone a syllabus 
- [x] Professors should be able to edit a cloned syllabus 

### Tasks

- [x] https://github.com/Qiskit/platypus/issues/1512
- [x] ~https://github.com/Qiskit/web-components/issues/153~
- [x] https://github.com/Qiskit/qiskit.org/issues/2770
- [x] https://github.com/Qiskit/qiskit.org/issues/2769
- [x] https://github.com/Qiskit/platypus/issues/1513
- [x] https://github.com/Qiskit/platypus/issues/1514
- [x] https://github.com/Qiskit/platypus/issues/1515
- [x] #1626
- [x] Announce on Twitter

**Comment by pandasa123** [comment]
I would like a single page that demonstrating these two, since they complement each other. As for what's interesting:

- Syllabus: This can cover a broad set of topics...seeing the title and a preview of the materials is interesting (possibly time to completion, but that can be out of scope for now)
- Problem Sets: I think the topic, number of problems, and difficult (out of scope) will be interesting in a list format

**Comment by pandasa123** [comment]
I've created a [very very rough mockup in Mural](https://app.mural.co/t/ibmquantum0809/m/ibmquantum0809/1657563880590/548dbedb9cbf08407711e732d9b96b211cf45fdc?sender=sanket0836) for how this should look

**Comment by pandasa123** [comment]
Meeting with @techtolentino + @gracelindsell:

**Syllabus Bank**

- Syllabus Bank can be a tile on Learn page
- Bank page will link out to multiple Syllabus pages (`/syllabus/<CODE>`)

**Duplicating Syllabus**

- There should be a button on every Syllabus to allow anyone to duplicate 
- If a user is logged in, it should direct them to `/syllabus/edit/<NEW CODE>` (and show up in their Classroom section)
- If they're not logged in, route to log in screen

**Comment by pandasa123** [comment]
Meeting with @gracelindsell + @techtolentino:

Looks like we have three bodies of work

**Duplicate Syllabus Button**

- Present on all Syllabi
- If logged in, this reroutes the user to the `/syllabus/edit/<CODE>` page with the Syllabus details section empty
- If logged out, we prompt the account creation flow + direct them to `/syllabus/edit/<CODE>` page (@techtolentino to explore feasibility)

**Classroom Empty State**

- The Classroom page should have a `Curated Syllabi` section that's always present with the curated syllabi
- User `Published Syllabi` should be first if present
- `Curated Syllabi` should not be dismissible / deletable

**Discoverability**

- Adding two tabs to the `Learn` page
- The first, `Learn`, contains all course content etc
- The second, `Teach`, contains Curated Syllabi, Problem Sets, etc

**Next Steps**

- @gracelindsell: higher fidelity prototype
- @techtolentino: investigating logged out redirection flow
- @pandasa123: review launch plan (announcement banner) + reaching out for authors to drive adoption

**Comment by pandasa123** [comment]
Yep, will keep that in mind as we curate 5+ high quality syllabi over time

**Comment by pandasa123** [comment]
Creating an issue for release plan

**Comment by JRussellHuffman** [comment]
Thanks for showing this work during sprint review this morning. Do these pages have all the instrumentation we want to gather data about this initial release?

**Comment by JRussellHuffman** [comment]
A few thoughts regarding the links to external pages. 

When linking externally, we should use the "launch" icon after the URL to indigate it's going to a page outside of our domain. It should also open in a new tab if it's outside of Qiskit.org.

Do we know we have permission, regarding copyright, to link out to these pages? This last point was brought up @AGFQ, so we may need more discussion here.

**Comment by JRussellHuffman** [comment]
Leaving a note here to follow up on user testing, now that we have finished material.

**Comment by pandasa123** [comment]
> Do these pages have all the instrumentation we want to gather data about this initial release?

Yep! We have Segment + Amplitude ready to track visits, clicks -- but only if users allow us to track

> When linking externally, we should use the "launch" icon after the URL to indigate it's going to a page outside of our domain. It should also open in a new tab if it's outside of Qiskit.org.

I think that's a great idea. We can add that as a future improvement?

> Do we know we have permission, regarding copyright, to link out to these pages? 

Definitely needs more discussion, but it should be ok since these are public links -- all open access

> User testing

100%. This should tell us if #1526 is a hugely detrimental problem to learning

**Comment by pandasa123** [comment]
Amazing launch everyone, closing this issue out!
