### ISSUE TITLE
As a professor, I want to ensure my students answer multiple choice questions without seeing the answer, so that I can ensure they understand the material

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#1419]
### Background

Server side MCQ. Professors need a way to ensure their students actually understand the material, rather than clicking multiple times. This is a starting step to having Problem Sets being graded on the server side for Assessments, where Professors can assign a Problem Set and collect all their student submission data 

### Goal

> Extend the MCQ question format to allow server-side grading + storing

### Acceptance criteria

- [ ] Students submit their MCQ selection to Autograder
- [ ] Students see MCQ `correct` / `incorrect` feedback after clicking "Submit"
- [ ] Content writer can enable server side grading on MCQ

### Future of feature

In the future:
- Students should be able to submit their whole problem set for grading and receiving a single grade for the problem set
- Professors should be able to see student MCQ selections + code submissions

### Tasks

- [ ] Grading function on server (< S)
- [ ] Modifying the MCQ widget to send to server (S)
- [ ] Showing feedback based on server response (S)

Submission

- [ ] Localstorage first (S), explore server side endpoint for problem set draft later if local storage is causing issues (M?)
- [ ] Only allow one submission for the entire problem set

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
