### ISSUE TITLE
As a learning, I want to access the written material associated with "Single Systems" video lecture.

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/platypus#1613]
### Background
As the first video lecture for "Understand Quantum Information and Computation" nears completion, we need to have the written material published and accessible prior to the video release.

### Goal

Add the "Single Systems" page to the UI, including space for the following units.

### Acceptance criteria

- [x] create the Single Systems page
- [x] create the "Basics of Quantum Information" overview card
- [x] add a card to the textbook home page for "basics of quantum information

### Out of scope

For now, the goal is to just publish the Single Systems page. The other two pages in the unit will have "under construction" graphics.

### Tasks
- [x] https://github.com/Qiskit/platypus/pull/1629
- [x] https://github.com/Qiskit/qiskit.org/pull/2842
- [x] https://github.com/Qiskit/qiskit.org/pull/2831
- [x] https://github.com/Qiskit/platypus/pull/1643
- [x] add to megamenu (qiskit.org)

**Comment by vabarbosa** [comment]
can this be closed?

**Comment by JRussellHuffman** [comment]
Is the material published live? I don't see it yet.

**Comment by vabarbosa** [comment]
@frankharkins @JRussellHuffman 

the content is live: https://learn.qiskit.org/course/basics

however, it is not added in the megamenu. 

under which topic (i.e., `Courses`, `Chapters`, etc.) should it be included?
