### ISSUE TITLE
As a learner, I want to access all versions of the Textbook from a single platform, so I continue my education with minimum confusion

### ISSUE THREAD

**Issue by vabarbosa** [Qiskit/platypus#2046]
### Background

various version of the Textbook is located across multiple platforms/domains. this makes it difficult to keep the content is sync and find where specific information exists.

### Goal

to provide a single platform/domain for all Textbook content/versions

### Acceptance criteria

all textbook content is available from same platform/domain

### Resources

- https://qiskit.org/learn/
- https://qiskit.org/textbook/

### Tasks

- [x] add versioned content
- [x] add card to versioned content
- [x] set up redirection of previous version (`cloud-deployment # 5676/5700`)
- [x] remove beta labeling/messaging
- [ ] update https://github.com/Qiskit/textbook repo (readme messaging, disable issues)

### PRs

- https://github.com/Qiskit/platypus/pull/2042
- https://github.com/Qiskit/qiskit.org/pull/3105
- https://github.com/qiskit-community/qiskit-textbook/pull/1567
- https://github.com/Qiskit/platypus/pull/2066
- https://github.com/qiskit-community/qiskit-textbook/pull/1574

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
