### ISSUE TITLE
As a textbook user, I want to learn quantum machine learning, so that I can expedite my understanding of QML without reading the whole textbook.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#251]
- [x] Coordinate with Edu team (Anna/Frank) 
- [x] Include the appropriate basic interactions in the learning path (glossary, variables, and exercises)
  - [x] add annotations for vocab Qiskit/qiskit.org#2226 
  - [x] add annotations for math #2227
  - [x] add at least 1 quiz per page Qiskit/platypus#249
  - [x] mini composer implementation for expressability Qiskit/qiskit.org#2229
  - [x] update circuit color scheme to match our brand. Qiskit/qiskit.org#2230
- [x] Migrate content to Platypus 
- [x] Include 1 custom interaction in the learning path 
  - [x] create amplitude disk component to be reusable, specifically for the "basis encoding" in the QML course and "Adding Amplitudes in the Intro Course Qiskit/qiskit.org#2231
  - [x] QML approaches table Qiskit/qiskit.org#2232
- [x] Make graphics match the textbook styling.
  - [x] redraw data vis diagrams in data vis style Qiskit/qiskit.org#2233
  - [x] redraw other graphics in sketchy style Qiskit/qiskit.org#2234
- [x] Qiskit/qiskit.org#2304
- [x] Qiskit/qiskit.org#2305

Out of scope items
  - [ ] mini composer needs "RZ" and "RX" gates (out of scope for now)
  - [ ] mini composer needs basic simulation (out of scope for now)

Design file for this work is here: https://www.figma.com/file/OTsy3nf8RCurAneByCd9S7/QML-course?node-id=35%3A4111

**Comment by lerongil** [comment]
Good work team!
