### ISSUE TITLE
User account: GDPR and Export Control Compliancy Checklist

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#261]
Per user story Qiskit/platypus#258, we will need to review the authentication and authorization service we provide to users via oauth. This might include:

- [x] Review data collected 
- [ ] Review data stored and length of time stored 
- [ ] Review what to do with data after deletion request
- [ ] Scope EULA for Textbook

**Comment by pandasa123** [comment]
We should be collecting the following information from our users:

**From All Users**

- **Email Address**: We need this for account creation, event marketing, nurture etc
- **Full Name**: This is for experience personalisation
- **Consent for Emails**: Self-explanatory
- **Years of Experience in Quantum**:  Demographic information
- **Department**: Demographic information

**Specifically Professors** 

- **Institution**: Our OKRs refer to adoption by university courses
- **Course Name**: Professors teach multiple courses, we need to support this so students know which course they're enrolling

**Possible Feature-Based Requirements**

- **Age**: If we're going to allow [teachers to create their own content](https://github.com/Qiskit/qiskit.org/issues/2215), we might need to collect this for COPPA requirements

**Comment by vabarbosa** [comment]
This repository is no longer maintained. It has been superseded by [IBM Quantum Learning](https://learning.quantum.ibm.com).
