### ISSUE TITLE
As a learner, I want a single unified learning portal for everything Qiskit so that I don't have to jump around looking for content.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#407]
In order to move to GA by Feb 21st, the following acceptance criteria should be met: 

## Bugs
- [ ] Math highlighting Qiskit/platypus#428
- [ ] stretch goal of fixing Qiskit/platypus#447 , Qiskit/platypus#466 
- [ ] review code cells in priority pages are functional 

## Migrating 
- [ ] redirect links from old textbook to new ones Qiskit/platypus#426 
- [ ] make new textbook pages indexible 
- [ ] Remove beta language from new textbook and under construction language for non-under constructive items 
- [ ] update/migrate qiskit.org/learn to learn.qiskit.org
- [ ] Replace learn.qiskit.org with the textbook home page

## Features
- [ ] Link to source in github (as mvp instead of download as notebook and open in IQX buttons)

## Content
- [x] update mega menu to include courses and other new content
- [x] update cards on textbook home page to include chapters
- [x] update cards on textbook home page to include tutorials
- [x] include an overview page for each card on the textbook

## Accessibility
- [ ] verify that everything is accessible prior to moving past beta

To do: review priority pages 
(leron): subtly check on copyright

**Comment by JRussellHuffman** [comment]
Latest designs: https://www.figma.com/file/X9p7omJAZncvDpg2IJLS6J/407-learn-page-migration?node-id=0%3A1

**Comment by lerongil** [comment]
Closing this one out! Great work team.
