### ISSUE TITLE
Redirect URLs in Platypus 

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#538]
- [x] https://qiskitorg-git-feature-textbook-demo-qiskit.vercel.app/textbook-demo should be qiskit.org/textbook-beta Qiskit/qiskit.org#1930
- [x] learn.qiskit.org should redirect to qiskit.org/textbook-beta Qiskit/platypus#532
- [x] if a user visits learn.qiskit.org/textbook, the user should be taken to qiskit.org/textbook-beta Qiskit/platypus#528
