### ISSUE TITLE
As a textbook visitor, I want to explore the learning material seamlessly from any spot in my learning journey.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#571]
Acceptance Criteria:

- [x] "browse all content" (the mega menu/mega dropdown done in Qiskit/qiskit.org#1466) is available from any page Qiskit/platypus#569 
- [x] the user can filter the mega menu by title Qiskit/qiskit.org#1808 
- [x] entering some text will display all the titles containing that text Qiskit/qiskit.org#1808
- [x] entering several words (separated by blanks) will display all the titles containing at least one of the words Qiskit/qiskit.org#1808
- [x] consistent with home page "browse all content" experience 
- [x] selections open up in a new tab
