### ISSUE TITLE
As a textbook visitor, I want to see the chapter index so that I can quickly view and skip to different parts within a page.

### ISSUE THREAD

**Issue by lerongil** [Qiskit/platypus#572]
- [x] chapter index added to left side panel - [#1820](Qiskit/platypus#562)
- [x] auto-generated chapter index based off of header titles - [#1822](Qiskit/platypus#560)
- [x] highlights currently viewed section - [#1809](Qiskit/platypus#568)
- [x] section highlights changes as user scrolls through the page - [#1809](Qiskit/platypus#568)
- [x] sections are clickable and when clicked users jump too the beginning of clicked section - [#1810](Qiskit/platypus#567)
