### ISSUE TITLE
As a Professor, I want to be able to create a dynamic syllabus, so that I can curate the learning experience for my students. 

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/platypus#676]
## Background

Professors have a curriculum or general topics they want to teach their students. They typically turn to the Qiskit Textbook as a resource for hands-on experimentation. Currently, Professors have to painstakingly collect Qiskit Textbook links themselves, order a subset into a syllabus, and share via static documents

## Goal

Professors should be able to create and share their own curated syllabus

## Acceptance Criteria:

- [x] Professors should be able to create their own course overview page that shows their institution's name and their course name  
- [x] Professors should be able to add and order Qiskit Textbook links to their custom course overview page (syllabus)
- [x] Each syllabus, at this MVP stage, would be an ordered list of Qiskit Textbook links 
- [x] Professor should be able to select Qiskit Textbook, Lab, Summer School, Project content into a syllabus
- [x] Each syllabus will have a unique URL that is publicly sharable
- [x] [Review Syllabus designs with Professors](https://github.com/Qiskit/platypus/issues/753)
- [ ] Validate Syllabus Feature with Professors 

**Other**

- [ ] Instrument syllabus creation + visits into Segment
   - [ ] How many syllabi created per account?
   - [ ] How many people visit a syllabus?
   - [ ] For people who visited a syllabus, how many of them started reading the learning material in the syllabus?

## Design

https://www.figma.com/file/f1QMqiXSgt2FCt0itvsA24/676-Professor-Syllabus?node-id=0%3A1

## Tasks

Setup:
- [x] #747
- [x] #748
- [x] #749

[Syllabus v1](https://github.com/Qiskit/platypus/milestone/1):

- [x] #771 
- [x] #762 
- [x] #763 
- [x] #764 
- [x] #765 
- [x] #766 
- [x] #767 
- [x] #768 
- [x] #769
- [x] #770 
- [x] #835
- [x] #836

[Syllabus v1.1](https://github.com/Qiskit/platypus/milestone/3):
- [ ] #813
- [ ] #814

[Syllabus v1.2](https://github.com/Qiskit/platypus/milestone/2):

- [ ] #772 
- [ ] #773 

[Syllabus v1.3](https://github.com/Qiskit/platypus/milestone/4):

- [ ] #775 
- [ ] #815

[Syllabus v.1.4](https://github.com/Qiskit/platypus/milestone/5):

- [ ] #776 
- [ ] #777

**Comment by pandasa123** [comment]
After talking to @JRussellHuffman and @gracelindsell, we realised that Course Overview page is a great "output", so we need to figure out the UI flow for a Professor creating a custom syllabus as "input"

**Comment by pandasa123** [comment]
**Architecture Review** with @gracelindsell, @eddybrando, @techtolentino, and @Tansito 

> This is a reasonably simple prototype

- Walked through @gracelindsell's prototype
- **Chapter Identifiers** (@eddybrando): What if we change the title or delete Textbook sections? We don't have chapter identifiers and this is something we might need to figure out later
- **Save to Syllabus** (@gracelindsell): "if a user can save a syllabus, and then can see the preview"...let's figure out a loader + toast once you save. If things are unsaved, we could change the focus colour. This could be a bit more complex from a technical perspective since we have to save + compare states (@eddybrando)
- **Deleting Content** (@eddybrando): Should we get a confirmation message? We could reuse the Account Deletion UX. Plus deletion could be save
- **Database**: We'll save this in our database, not Mathigon
- **What if a user deletes their account, what happens to the syllabus**: We're not sure yet but let's try to table this for now. Deleted account syllabi would stay
- **What should a shared preview be**: Let's keep this simple for now since it's a nice to have
- **Metrics**: Out of scope for now...let's wait until later

**Next Steps**

- [ ] @gracelindsell cleaning up prototype
- [ ] This has a dependency on User Accounts...once @Tansito merges #271, it should be ready

**Comment by pandasa123** [comment]
#753 completed

**Comment by lerongil** [comment]
v1 has been shipped and we will move v2 to a new user story. Great work to the syllabus feature dev, design, and product team.
